### ISSUE TITLE
 When I click on the star, nothing happens.

### ISSUE THREAD

**Issue by schieck0** [biblibre/kanboard-plugin-StarredProjects#2] opened 2019-07-18 14:21 UTC
When I click on the star, nothing happens.
A request is made, with return 200, but the project is not stared.

**Comment by schieck0** [comment] 2019-07-18 14:22
MySQL database


When I manually add a record to the table, the project gets marked. Unmark "works", but does not remove from table and on refresh goes back to old state.

**Comment by jajm** [comment] 2019-07-18 14:30
Which version of Kanboard are you using ?

**Comment by schieck0** [comment] 2019-07-18 14:36
Application version: 1.2.10
PHP version: 7.2.0
PHP SAPI: fpm-fcgi
HTTP Client: cURL
OS version: Linux 4.4.180-1.el6.elrepo.x86_64
Database driver: mysql
Database version: 5.6.36-log

**Comment by jajm** [comment] 2019-07-18 15:03
I can't reproduce the issue.

Clicking on a star should make a request to `/starproject`. Is it what you see ? What is returned by this request ? It should return a JSON object with a `status` property.

**Comment by schieck0** [comment] 2019-07-18 16:38
Returns the complete html of the page

**Comment by schieck0** [comment] 2019-07-18 18:44
![image](https://user-images.githubusercontent.com/9256271/61483273-dcf63680-a972-11e9-9a24-08470174215f.png)

**Comment by eSkiSo** [comment] 2019-08-01 11:18
I was able to get it to work by changing in assets/js/starred_projects.js
**From**
`$.ajax('starproject?project_id=' + project_id).done(function(data) {`
**To**
`$.ajax('?controller=StarredProjectsController&action=starProject&plugin=StarredProjects&project_id=' + project_id).done(function(data) {`

Its seems the route is not being set correctly, i've tried to change it a few times and none work, only this did,

**Comment by jajm** [comment] 2019-08-07 08:31
Have you enabled [URL rewriting](https://docs.kanboard.org/en/latest/admin_guide/url_rewriting.html) ?

**Comment by jajm** [comment] 2019-08-07 09:00
I pushed a fix for when URL rewriting is disabled. Can you retry on latest master ?

**Comment by schieck0** [comment] 2019-08-08 19:31
> I pushed a fix for when URL rewriting is disabled. Can you retry on latest master ?

Yes ,it works! Thanks

**Comment by jajm** [comment] 2019-08-12 08:53
Fixed by f8d1a02b9a6f8729d3856f6b8bbd2b38026d6c93

**Closed as completed by jajm** 2019-08-12 08:53 UTC
